from pydantic import BaseModel
from typing import Optional

chat_sessions: dict = {}

class ChatRequest(BaseModel):
    session_id: Optional[str] = None  # Auto-generated by server if not provided
    message: str